In [7]:
from bpd.io import load_dataset
import numpy as np

In [3]:
path = "/pscratch/sd/i/imendoza/data/cache_chains/exp73_51/g_samples_boots_9940.npz"

In [4]:
ds = load_dataset(path) 
ds['plus'].keys()

dict_keys(['g1', 'g2', 'a_logflux', 'mean_logflux', 'mean_loghlr', 'sigma_e', 'sigma_logflux', 'sigma_loghlr'])

In [5]:
ds['plus']['g1'].shape, ds['plus']['mean_logflux'].shape

((2, 1000), (2, 1000))

In [6]:
# ds['minus']['g1'][1]

In [9]:
ds['plus']['g1'].mean(), ds['minus']['g1'].mean()

(np.float64(0.02072587354642636), np.float64(-0.019277458420532682))

In [10]:
ds['plus']['sigma_e']

array([[0.20000343, 0.2000285 , 0.20010307, ..., 0.19992327, 0.19994097,
        0.19991204],
       [0.20054872, 0.20052958, 0.20021259, ..., 0.20038171, 0.20034515,
        0.20017366]], shape=(2, 1000))

In [13]:
ds['plus']['a_logflux']

array([[13.78701179, 13.79187968, 13.78468199, ..., 13.98495753,
        13.8700135 , 13.92236955],
       [14.29212638, 14.28674501, 14.27500754, ..., 13.90811473,
        13.90859924, 13.84185803]], shape=(2, 1000))

In [14]:
ds['plus']['sigma_logflux']

array([[0.40140013, 0.40159454, 0.40162846, ..., 0.40116289, 0.40289479,
        0.40215217],
       [0.40012131, 0.39988945, 0.39978867, ..., 0.39961498, 0.39962669,
        0.39932121]], shape=(2, 1000))

# Setting with all free

In [21]:
dsp = load_dataset("/pscratch/sd/i/imendoza/data/cache_chains/exp73_51/shear_samples_512_plus.npz")
dsm = load_dataset("/pscratch/sd/i/imendoza/data/cache_chains/exp73_51/shear_samples_512_minus.npz")

g1p = dsp['samples']['g1']
g1m = dsm['samples']['g1']
mfull = (g1p.mean() - g1m.mean()) / 2/ 0.02 - 1 
mfull / 1e-3

np.float64(-0.3130202324510556)

In [14]:
paths = [f"/pscratch/sd/i/imendoza/data/cache_chains/exp73_51/g_samples_boots_994{i}.npz" for i in range(0,4)]
ms = []
for p in paths:
    ds = load_dataset(p)
    g1p = ds['plus']['g1'].mean(1)
    g1m = ds['minus']['g1'].mean(1)
    print(g1p)
    print(g1m)
    m = (g1p - g1m) / 2/ 0.02 - 1
    ms.append(m)

[0.02044024 0.02101151]
[-0.01956343 -0.01899149]
[0.02108911 0.02076432]
[-0.01891191 -0.01922609]
[0.02058738 0.01965532]
[-0.01941324 -0.02032691]
[0.02009666 0.02030613]
[-0.01991209 -0.01968038]


In [24]:
_ms = np.concatenate(ms)
_ms / 1e-3

array([ 0.09156915,  0.0750292 ,  0.02549806, -0.23979181,  0.01533466,
       -0.44423441,  0.21875551, -0.33740457])

In [25]:
_ms.mean() / 1e-3

np.float64(-0.07440552766546649)